### ISSUE TITLE
New field additionalUserData.data is hardly usable

### ISSUE THREAD

**Issue by zioc** [rancher/cluster-api-provider-rke2#212]
**What happened:**

While trying to use the new additionalUserData.data field that was added in https://github.com/rancher-sandbox/cluster-api-provider-rke2/pull/190, it turned out to be hardly usable:
- As data attribute type is `map[string]string`, it does not bring much value over previous config field, as each config item has to be provided as a string, which is hard to merge/patch
- As it is using [gotpl rendering](https://github.com/Danil-Grigorev/cluster-api-provider-rke2/blob/f62ad18a522bac9b88ad1b8945268b69572fd33f/bootstrap/internal/cloudinit/cloudinit.go#L90-L93) to format the data field, it may lead to unpredictable results.

**What did you expect to happen:**

Have the ability to provide data as a `map[string]interface{}`

**How to reproduce it:**

This kind of configuration
```
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: RKE2ControlPlane
  metadata:
    name: management-cluster-control-plane
    namespace: default
  spec:
    agentConfig:
      additionalUserData:
        data: 
           bootcmd: |                                               
             - echo "hello"                                                        
             - echo "world"       
```

Will lead to following failure:

```
E1201 17:17:27.437268       1 controller.go:324]  "msg"="Reconciler error" "error"="failed to unmarshal arbitrary cloud-init data: yaml: line 2: block sequence entries are not allowed in this context, please check if you put valid yaml data: \nbootcmd: - echo \"hello\"\n- echo \"world\"" "RKE2Config"={"name":"management-cluster-control-plane-5w9d8","namespace":"default"} "controller"="rke2config" "controllerGroup"="bootstrap.cluster.x-k8s.io" "controllerKind"="RKE2Config" "name"="management-cluster-control-plane-5w9d8" "namespace"="default" "reconcileID"="46baa075-8d0b-49a9-8c82-5a17dcd4fd7f"
```

As the template is rendering bootcmd as:

```
$ echo -e "data: \nbootcmd: - echo \"hello\"\n- echo \"world\""
data: 
bootcmd: - echo "hello"
- echo "world"
```

**Anything else you would like to add:**

It would be really desirable to have a field using map[string]interface{} format, or maybe even better map[string}*[apiextensions.JSON](https://pkg.go.dev/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions#JSON), in order to be able to provide data as a plain object, eg:

```
        data: 
           bootcmd:                                         
             - echo "hello"                                                        
             - echo "world"       
```

**Comment by mikeruu** [comment]
I'm having the same issue trying to pass cloud-config data. Can you please share a working example?

```
	failed to unmarshal arbitrary cloud-init data: yaml: line 2: block sequence entries are not allowed in this context, please check if you put valid yaml data:
	users: - name: ubuntu
	  ssh_authorized_keys:
	    - ssh-rsa
```

this is the Yaml definition 

```
  agentConfig:
    kubelet:
      extraArgs:
        - provider-id=metal3://{{ ds.meta_data.uuid }}
    nodeName: '{{ ds.meta_data.local_hostname }}'
    format: cloud-config
    additionalUserData:
      data:
        users: |
          - name: ubuntu
            ssh_authorized_keys:
              - ssh-rsa
```
