### ISSUE TITLE
Improve usability of ControlPlane's registrationMethod with Cluster Classes

### ISSUE THREAD

**Issue by anmazzotti** [rancher/cluster-api-provider-rke2#343]
**Describe the solution you'd like:**
Due to validation of the `RKE2ControlPlane.spec.registrationMethod`, it is not currently possible to use `registrationMethod: "address"` in ClusterClasses without providing a valid `registrationAddress` too.

Even with patching this value afterwards, like:

```yaml
    - jsonPatches:
      - op: replace
        path: /spec/template/spec/registrationAddress
        valueFrom:
          variable: myRegistrationAddress
```

This will fail with:

```
The RKE2ControlPlane "rke2-control-plane" is invalid: spec.registrationAddress: Invalid value: "": registrationAddress must be supplied when using registration method 'address'
```

As the initial RKE2ControlPlane is created with empty `registrationAddress`, before patching.

One workaround is to configure the initial registrationMethod to `control-plane-endpoint` or any other default that does not require validation. 

Then I think one patch should replace both values ad the same time:

```yaml
    - jsonPatches:
      - op: replace
        path: /spec/template/spec/registrationMethod
        value: "address"
      - op: replace
        path: /spec/template/spec/registrationAddress
        valueFrom:
          variable: myRegistrationAddress
```

I did not test it, but it should technically work.
The drawback of this workaround however, is that initially the RKE2ControlPlane object is created with a different registrationMethod. This could lead to race condition issues where maybe nodes are joining using an unwanted registration method.

It should be fine on the initial cluster creation, assuming the first node ever will be the first control plane node, so there will be nothing to register on yet, and after that (or even before bootstrapping this node), the registrationMethod should be patched to the user defined value.

Could be more tricky however on a control plane rollout or during other upgrade scenarios.

**Why do you want this feature:**
I want to avoid having to configure a default `registrationMethod` for the real one to be patched later, if this could lead to problems.
