### ISSUE TITLE
Unable to use release v0.5.0

### ISSUE THREAD

**Issue by jisnardo** [rancher/cluster-api-provider-rke2#374]
**What happened:**

Error: invalid provider metadata: version v0.5.0 (one of the available versions) for the provider rke2-bootstrap-system/bootstrap-rke2-bootstrap does not match any release series

**What did you expect to happen:**

Upgrade from v0.4.1

**How to reproduce it:**

```
demo@test:~$ kind create cluster -n bootstrap
Creating cluster "bootstrap" ...
 ✓ Ensuring node image (kindest/node:v1.27.3) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-bootstrap"
You can now use your cluster with:

kubectl cluster-info --context kind-bootstrap

Thanks for using kind! 😊
```

`demo@test:~$ kind get kubeconfig -n bootstrap > ~/.kube/config-kind-bootstrap`

```
[kind-bootstrap|default] demo@test:~$ cat .cluster-api/clusterctl.yaml

...
providers:
  - name: "cluster-api"
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/latest/core-components.yaml"
    type: "CoreProvider"

  - name: "rke2"
    url: "https://github.com/rancher/cluster-api-provider-rke2/releases/latest/bootstrap-components.yaml"
    type: "BootstrapProvider"

  - name: "rke2"
    url: "https://github.com/rancher/cluster-api-provider-rke2/releases/latest/control-plane-components.yaml"
    type: "ControlPlaneProvider"

  - name: "vsphere"
    url: "https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/latest/infrastructure-components.yaml"
    type: "InfrastructureProvider"

  - name: "in-cluster"
    url: "https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/releases/latest/ipam-components.yaml"
    type: "IPAMProvider"
```

`[kind-bootstrap|default] demo@test:~$ export GITHUB_TOKEN=ghp_...`

```
[kind-bootstrap|default] demo@test:~$ clusterctl init --bootstrap rke2 --control-plane rke2 --infrastructure vsphere --ipam in-cluster
Fetching providers
Installing cert-manager Version="v1.13.1"
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v1.7.4" TargetNamespace="capi-system"
Installing Provider="bootstrap-rke2" Version="v0.4.1" TargetNamespace="rke2-bootstrap-system"
Installing Provider="control-plane-rke2" Version="v0.4.1" TargetNamespace="rke2-control-plane-system"
Installing Provider="infrastructure-vsphere" Version="v1.10.2" TargetNamespace="capv-system"
Installing Provider="ipam-in-cluster" Version="v0.1.0" TargetNamespace="capi-ipam-in-cluster-system"

Your management cluster has been initialized successfully!

You can now create your first workload cluster by running the following:

  clusterctl generate cluster [name] --kubernetes-version [version] | kubectl apply -f -
```

```
[kind-bootstrap|default] demo@test:~$ clusterctl upgrade plan 
Checking cert-manager version...
Cert-Manager is already up to date

Checking new release availability...
Error: invalid provider metadata: version v0.5.0 (one of the available versions) for the provider rke2-bootstrap-system/bootstrap-rke2 does not match any release series
```

**Anything else you would like to add:**

n/a

**Environment:**

kind version 0.20.0
