### ISSUE TITLE
Investigate running CAPRKE2 on Azure

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/cluster-api-provider-rke2#438]
Investigate running CAPRKE2 on Azure

**Comment by yiannistri** [comment]
CAPZ supports both Managed (AKS) and Self-managed clusters. Using CAPRKE2 is feasible for Self-managed clusters.
CAPZ also supports different identity methods:
- Workload Identity which requires an OIDC issuer
- Service Principal
- Service Principal with Certificate
- User-Assigned Managed Identity which requires a management cluster running in Azure.

For this investigation we will use a Service Principal as that requires the least amount of configuration / moving parts.

**Comment by yiannistri** [comment]
Before using CAPRKE, we created a CAPZ self-managed cluster to ensure permissions were correctly setup:

1.  We created a Service Principal using `az ad sp create-for-rbac --role Contributor --scopes /subscriptions/$AZURE_SUBSCRIPTION_ID`
2. On a newly created kind cluster we run `clusterctl init --infrastructure azure`
3. We generated a workload cluster definition 
```
clusterctl generate cluster my-cluster --kubernetes-version 1.29.1 --control-plane-machine-count 1 --worker-machine-count 1  > cluster.yaml
```
4. The generated cluster definition uses Workload Identity by default, we changed this to use Service Principal instead 
```
yq -i "with(. | select(.kind == \"AzureClusterIdentity\"); .spec.type |= \"ServicePrincipal\" | .spec.clientSecret.name |= \"${AZURE_CLUSTER_IDENTITY_SECRET_NAME}\" | .spec.clientSecret.namespace |= \"${AZURE_CLUSTER_IDENTITY_SECRET_NAMESPACE}\")" cluster.yaml
```
    
 We also updated the `AzureMachineTemplate` definiton to remove `spec.template.spec.identity` and `spec.template.spec.userAssignedIdentities`. Then we applied the cluster definition `kubectl apply -f cluster.yaml`

 5. To get a working cluster we also had to install [a cloud provider](https://cluster-api.sigs.k8s.io/user/quick-start.html#install-a-cloud-provider) and deploy a [CNI solution](https://cluster-api.sigs.k8s.io/user/quick-start.html#deploy-a-cni-solution)

With that out of the way, we can now focus on using CAPRKE2 for our control plane.

**Comment by yiannistri** [comment]
1. On a kind cluster, install latest version of CAPI, CAPZ and CAPRKE2 providers.

```
kind create cluster
clusterctl init --core cluster-api:v1.8.3 --bootstrap rke2:v0.7.0 --control-plane rke2:v0.7.0 --infrastructure azure:v1.17.0
```

2. Update the CAPZ controller to include the following flag 

```
--bootstrap-config-gvk=RKE2Config.v1beta1.bootstrap.cluster.x-k8s.io
```

3.  After checking that all the pods are running fine, apply the following cluster manifest:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rke2config-reader
rules:
- apiGroups: ["bootstrap.cluster.x-k8s.io"]
  resources: ["rke2configs"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-rke2configs-capz-manager
subjects:
- kind: ServiceAccount
  name: capz-manager
  namespace: capz-system
roleRef:
  kind: ClusterRole
  name: rke2config-reader
  apiGroup: rbac.authorization.k8s.io
```

4. 
5.
