### ISSUE TITLE
Add ConfigMap support as FileSource for write_files configuration

### ISSUE THREAD

**Issue by banschikovde** [rancher/cluster-api-provider-rke2#565]
**Describe the solution you'd like**:

Add support for ConfigMaps as a FileSource in write_files configuration for cloud-init. Similar to the existing SecretFileSource functionality, we need the ability to reference ConfigMap data when generating files during initialization. This will allow getting file content from either Secrets or ConfigMaps depending on the use case.

**Why do you want this feature:**

Currently file content can only be sourced from Secrets, which is limiting for non-sensitive configuration data
ConfigMaps are the standard Kubernetes way to handle non-sensitive configuration
This will provide more flexibility in managing configuration data
Users can better separate sensitive data (in Secrets) from regular configuration (in ConfigMaps)

**Anything else you would like to add:**

The implementation should maintain backwards compatibility with existing SecretFileSource
Only one source type (Secret or ConfigMap) should be allowed at a time for a given file
This enhancement follows the standard Kubernetes pattern of using ConfigMaps for configuration data
Documentation will need to be updated to reflect the new ConfigMap support

**Comment by valaparthvi** [comment]
Before I go ahead any further, there are some things I would like to clear up.
1. The `FileSource` referenced in the description is [this](https://github.com/rancher/cluster-api-provider-rke2/blob/main/bootstrap/api/v1alpha1/rke2config_types.go#L314)? And the issue is about adding support for `ConfigMapFileSource` as an alternative to the `SecretFileSource`?
2. I went through the [listed bootstrap providers](https://cluster-api.sigs.k8s.io/reference/providers#bootstrap) to check if there was any reference to the ConfigMap, but found none, so I assume this is a new feature we want to introduce to RKE2. Please correct me if I am wrong.
3. The reference example I found for existing FileSource is [this](https://cluster-api.sigs.k8s.io/tasks/bootstrap/kubeadm-bootstrap/#additional-features) and [this too](http://caprke2.docs.rancher.com/02_topics/03_cis-psa.html#cis-and-pod-security-admission).
```yaml
files:
- contentFrom:
    secret:
      key: node-cloud.json
      name: ${CLUSTER_NAME}-md-0-cloud-json
  owner: root:root
  path: /etc/kubernetes/cloud.json
  permissions: "0644"
- path: /etc/kubernetes/cloud.json
  owner: "root:root"
  permissions: "0644"
  content: |
    {
      "cloud": "CustomCloud"
    }
```
So, after this feature the above manifest would look like this, not very different from `SecretFileSource`:
```yaml
files:
- contentFrom:
    configMap:
      key: node-cloud.json
      name: ${CLUSTER_NAME}-md-0-cloud-json
  owner: root:root
  path: /etc/kubernetes/cloud.json
  permissions: "0644"

- contentFrom:
    secret:
      key: node-cloud.json
      name: ${CLUSTER_NAME}-md-0-cloud-json
  owner: root:root
  path: /etc/kubernetes/cloud.json
  permissions: "0644"
- path: /etc/kubernetes/cloud.json
  owner: "root:root"
  permissions: "0644"
  content: |
    {
      "cloud": "CustomCloud"
    }
```

Or should it also add support for `path` like here in this [example](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/configmap/configure-pod.yaml); [ref](https://kubernetes.io/docs/concepts/configuration/configmap/#configmaps-and-pods)?
>standard Kubernetes pattern of using ConfigMaps for configuration data

Based on this, I assume `ConfigMapFileSource` will work in the same way as `SecretFileSource`.

So far, I haven't found any tests for this, so any other reference would also be very helpful :)
