### ISSUE TITLE
serverConfig.cloudProviderName is ignored on initial control plane provisioning

### ISSUE THREAD

**Issue by anmazzotti** [rancher/cluster-api-provider-rke2#567]
**What happened:**

I configured the RKE2ControlPlane as follows:

```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: RKE2ControlPlane
metadata:
  name: capi-machinepool-control-plane
  namespace: default
spec:
  version:  v1.31.1+rke2r1
  replicas: 3
  registrationMethod: control-plane-endpoint
  rolloutStrategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
  agentConfig: {}
  serverConfig:
    cloudProviderName: external
    disableComponents:
      kubernetesComponents:
      - cloudController
    kubeAPIServer:
      extraArgs:
      - --anonymous-auth=true
```

On the downstream node however I miss the `cloud-provider-name: external`. 
Peeking at the bootstrap secret for the first control plane node, I can see this:

```yaml
-   path: /etc/rancher/rke2/config.yaml
    owner: root:root
    permissions: '0640'
    content: |
      disable-cloud-controller: true
      kube-apiserver-arg:
        - --anonymous-auth=true
      tls-san:
        - capi-machinepool-1024b3bf.germanywestcentral.cloudapp.azure.com
      cluster-cidr: 10.96.0.0/12
      service-cidr: 10.244.0.0/16
      token: foobar
```

All other settings but cloud-provider-name are propagated.

**What did you expect to happen:**
`/etc/rancher/rke2/config.yaml` should contain `cloud-provider-name: external`

**How to reproduce it:**

Apply the snippet above

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- rke provider version: v0.11.0
- OS (e.g. from `/etc/os-release`):
