### ISSUE TITLE
RKE2Config support for MachinePools

### ISSUE THREAD

**Issue by anmazzotti** [rancher/cluster-api-provider-rke2#569]
**Describe the solution you'd like:**
Currently the bootstrap controller [expects](https://github.com/rancher/cluster-api-provider-rke2/blob/release-0.11/bootstrap/internal/controllers/rke2config_controller.go#L222) a `RKE2Config` owned by a `Machine`.
However, when referenced by a `MachinePool`, the owner will be the `MachinePool` itself.

For example:

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: capi-machinepool-mp-0
  namespace: default
spec:
  clusterName: capi-machinepool
  replicas: 3
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: RKE2Config
          name: capi-machinepool-mp-0
```

```yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: RKE2Config
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: capi-machinepool
  name: capi-machinepool-mp-0
  namespace: default
  ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: MachinePool
      name: capi-machinepool-mp-0
      uid: 0d99ccb9-80d6-4842-b1de-0a6f9b05d7c5
spec:
  agentConfig:
    additionalUserData: {}
    format: cloud-config
  privateRegistriesConfig: {}

```

Also be aware that the [kubeadm implementation](https://github.com/kubernetes-sigs/cluster-api/blob/release-1.9/bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go#L330) does take special actions when the config is owner by a `MachinePool`.
Possibly this applies to RKE2 as well.

**Why do you want this feature:**

RKE2 support for MachinePools

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
