### ISSUE TITLE
Empty machineTemplate.infrastructureRef after rancher-turtles upgrade

### ISSUE THREAD

**Issue by Kristian-ZH** [rancher/cluster-api-provider-rke2#661]
**What happened:**
We upgraded rancher-turtles from `0.14.1` to `0.19.0`. This change upgraded rke2 provider from `v0.9.0` to `v0.15.1`.

The new provider has this change https://github.com/rancher/cluster-api-provider-rke2/pull/542/files  which moved the `infrastructureRef` under the `machineTemplate` field but the actual result of the `RKE2ControlPlane` was:

```
infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3MachineTemplate
    name: ha-cluster-controlplane
  machineTemplate:
    infrastructureRef: {}
    metadata: {}
  manifestsConfigMapReference: {}
```

Later we tried to upgrade the k8s version of the downstream machines (3 machines in HA mode) but they were stuck in `Deleting`

**What did you expect to happen:**
After the turtles upgrade the provider should update the RKE2ControlPlane resource like this

```
infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3MachineTemplate
    name: ha-cluster-controlplane
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: Metal3MachineTemplate
      name: ha-cluster-controlplane
      namespace: default
    metadata: {}
    nodeDeletionTimeout: 10s
    nodeDrainTimeout: 2m0s
    nodeVolumeDetachTimeout: 5m0s
  manifestsConfigMapReference: {}
```

**How to reproduce it:**
Fillow the intruction above

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- rke provider version: v0.15.1
- OS (e.g. from `/etc/os-release`): slm6.1
